##########################################
## INPUT 
##########################################

MvnRepo: urs-mvn


##########################################
## GLOBAL 
##########################################

ArtifactoryIntegration: artifactory_eu

Pipeline:
  mvnNname: backapp_mvn
  mvnContainerName: backapp_mvn_docker

##########################################
## MVN Pipeline
##########################################

GitRepoMvn:
  name: src_code_backapp_mvn
  gitProvider: yann_github
  path: cyan21/gs-multi-module
  branches:
    include: soleng-stg
  files:
    exclude: '^complete\/CI\/.+'
    include: '^complete\/.+'

MvnBuild:
  stepName: build_backapp_mvn
  goals: "clean package"
  sourceLocation:       complete/
  configFileLocation:   CI
  configFileName:       mvn-art-config
  forceXrayScan:        false
  autoPublishBuildInfo: true

XrayMvnStepName: scan_backapp_mvn

BuildInfoMvn:
  resourceName: bi_backapp_mvn
  name: backapp_mvn
  autoPublishBuildInfo: true

BuildInfoMvnPromotion:
  resourceName: bi_backapp_mvn_promoted_staging
  stepName: promote_bi_backapp_mvn
  includeDependencies: false
  status: SANDBOX_OK
  comment: Unit testing and Xray scan passed succesfully
  copy: false
  mvnPromoteRepo: urs-mvn-rc-local

FileSpecMvn:
  name: fs_backapp_mvn
  appName: multi-module-application 
  flat: true

PropertyBagMvn: pb_backapp_mvn

##########################################
## CONTAINER PIPELINE
##########################################

GitRepoContainer:
  name: src_dockerfile_backapp_mvn
  gitProvider: yann_github
  path: cyan21/gs-multi-module
  branches:
    include: soleng-stg
  files:
    include: '^complete\/CI\/Docker\/.+'

PropertyBagContainer: pb_backapp_mvn_container


## DOCKER PIPELINE
DockerBuild:
  stepName: backapp_mvn_docker
  dockerFileName: Dockerfile
  dockerFileLocation: complete/CI/Docker/
  registry: platform-us.staging.gcp.devopsacc.team/urs-docker
  imageName: backapp-mvn-docker
  artifactoryTargetRepoName: urs-docker-dev-local

BuildInfoContainer:
  resourceName: bi_backapp_mvn_docker
  name: backapp_mvn_docker
#  autoPublishBuildInfo: true

BuildInfoContainerPromotion:
  resourceName: bi_backapp_mvn_docker_promoted
  stepName: promote_bi_backapp_mvn_docker
  includeDependencies: false
  status: SCAN_OK
  comment: Xray scan OK 
  copy: false
  mvnPromoteRepo: urs-docker-rc-local

XrayMvnContainerStepName: scan_backapp_mvn_docker
